### ISSUE TITLE
Call to undefined method ErlandMuchasaj\LaravelGzip\Middleware\GzipEncodeResponse::hasMinimumContentLength()

### ISSUE THREAD

**Issue by JamieWBuzz** [erlandmuchasaj/laravel-gzip#10]
Updated to the latest version (1.1.4)

`vendor\erlandmuchasaj\laravel-gzip\src\Middleware\GzipEncodeResponse.php` on line 41

This was added in the latest release. However it doesn't seem to be referencing anything in file.

```
[2024-07-25 10:51:23] production.ERROR: Call to undefined method ErlandMuchasaj\LaravelGzip\Middleware\GzipEncodeResponse::hasMinimumContentLength() {"exception":"[object] (Error(code: 0): Call to undefined method ErlandMuchasaj\\LaravelGzip\\Middleware\\GzipEncodeResponse::hasMinimumContentLength() at /home/site/wwwroot/vendor/erlandmuchasaj/laravel-gzip/src/Middleware/GzipEncodeResponse.php:41)
[stacktrace]
#0 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): ErlandMuchasaj\\LaravelGzip\\Middleware\\GzipEncodeResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#1 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#2 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#3 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#4 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#5 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(51): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#6 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#7 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#8 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#9 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(110): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(183): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#17 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#18 /home/site/wwwroot/public/index.php(51): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#19 {main}
"} 
```

Caught it in our pre-live environment. Rolling back to 1.1.2 has it working again (1.1.3 did not work either)

**Comment by erlandmuchasaj** [comment]
Fixed
